target = main
sources = main.cpp mdfile.cpp mdfile.h
CC = g++
CCFlags = -Wall
LDLIBS = -lcrypto++
OPT = -Ofast
all:build
build:
$(CC) $(CCFlags) $(OPT) $(sources) -o $(target) $(LDLIBS)
dbg:
$(CC) -g $(sources) -o $(target)DBG